/*

 Copyright (c) 2006-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable
 format (e.g. HEX file) and only in or with products utilizing the Microsemi
 switch and PHY products.  The source code of the software may not be
 disclosed, transmitted or distributed without the prior written permission of
 Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all
 ownership, copyright, trade secret and proprietary rights in the software and
 its source code, including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL
 WARRANTIES OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES
 ARE EXPRESS, IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION,
 WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND
 NON-INFRINGEMENT.

*/
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf
 */
#ifndef DOT1AB_LLDP_H
#define DOT1AB_LLDP_H


#include "lldp_remote.h"

#define DOT1AB_LLDP  1

#define DOT1AB_SUPPORTED_LLDPOBJECTS     1

mesa_rc header_simple_entries_table(struct variable *vp,
                                    oid *name,
                                    size_t *length,
                                    int exact,
                                    size_t *var_len, WriteMethod **write_method,
                                    int oid_length,
                                    vtss_appl_lldp_remote_entry_t   *return_entry);

mesa_rc header_loc_port_num_table (struct variable *vp,
                                   oid *name,
                                   size_t *length,
                                   int exact,
                                   size_t *var_len,
                                   WriteMethod **write_method);

/*
 * function declarations
 */
#if DOT1AB_SUPPORTED_LLDPOBJECTS
/* lldpObjects ----------------------------------------------------------*/
void            init_lldpObjects(void);
FindVarMethod   var_lldpConfiguration;
FindVarMethod   var_lldpLocManAddrTable;
FindVarMethod   var_lldpStatsTxPortTable;
FindVarMethod   var_lldpRemTable;
FindVarMethod   var_lldpLocPortTable;
FindVarMethod   var_lldpPortConfigTable;
FindVarMethod   var_lldpConfigManAddrTable;
FindVarMethod   var_lldpRemManAddrTable;
FindVarMethod   var_lldpStatsRxPortTable;
FindVarMethod   var_lldpStatistics;
FindVarMethod   var_lldpLocalSystemData;
WriteMethod     write_lldpMessageTxInterval;
WriteMethod     write_lldpNotificationInterval;
WriteMethod     write_lldpMessageTxHoldMultiplier;
WriteMethod     write_lldpTxDelay;
WriteMethod     write_lldpReinitDelay;
WriteMethod     write_lldpPortConfigAdminStatus;
WriteMethod     write_lldpPortConfigNotificationEnable;
WriteMethod     write_lldpPortConfigTLVsTxEnable;
WriteMethod     write_lldpConfigManAddrPortsTxEnable;
#endif /* DOT1AB_SUPPORTED_LLDPOBJECTS */

#endif                          /* DOT1AB_LLDP_H */

