/*
 Copyright (c) 2006-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable
 format (e.g. HEX file) and only in or with products utilizing the Microsemi
 switch and PHY products.  The source code of the software may not be
 disclosed, transmitted or distributed without the prior written permission of
 Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all
 ownership, copyright, trade secret and proprietary rights in the software and
 its source code, including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL
 WARRANTIES OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES
 ARE EXPRESS, IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION,
 WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND
 NON-INFRINGEMENT.

*/
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef PBRIDGEMIB_H
#define PBRIDGEMIB_H


#ifdef VTSS_SW_OPTION_QOS
#define RFC4363_SUPPORTED_P_BRIDGE  1
#endif /* VTSS_SW_OPTION_QOS */

/*
 * function declarations
 */
void            init_rfc4363_p_bridge(void);
FindVarMethod   var_pBridgeMIB;
FindVarMethod   var_dot1dPortCapabilitiesTable;
FindVarMethod   var_dot1dPortPriorityTable;
FindVarMethod   var_dot1dUserPriorityRegenTable;
FindVarMethod   var_dot1dTrafficClassTable;
FindVarMethod   var_dot1dPortOutboundAccessPriorityTable;
FindVarMethod   var_dot1dPortGarpTable;
FindVarMethod   var_dot1dPortGmrpTable;
WriteMethod     write_dot1dTrafficClassesEnabled;
WriteMethod     write_dot1dGmrpStatus;
WriteMethod     write_dot1dPortDefaultUserPriority;
WriteMethod     write_dot1dPortNumTrafficClasses;
WriteMethod     write_dot1dRegenUserPriority;
WriteMethod     write_dot1dTrafficClass;
WriteMethod     write_dot1dPortGarpJoinTime;
WriteMethod     write_dot1dPortGarpLeaveTime;
WriteMethod     write_dot1dPortGarpLeaveAllTime;
WriteMethod     write_dot1dPortGmrpStatus;
WriteMethod     write_dot1dPortRestrictedGroupRegistration;
void            init_dot1dTpHCPortTable(void);
FindVarMethod   var_dot1dTpHCPortTable;
FindVarMethod   var_dot1dTpHCPortTable;


#endif                          /* PBRIDGEMIB_H */
