/*
 Copyright (c) 2006-2017 Microsemi Corporation "Microsemi". All Rights Reserved.

 Unpublished rights reserved under the copyright laws of the United States of
 America, other countries and international treaties. Permission to use, copy,
 store and modify, the software and its source code is granted but only in
 connection with products utilizing the Microsemi switch and PHY products.
 Permission is also granted for you to integrate into other products, disclose,
 transmit and distribute the software only in an absolute machine readable
 format (e.g. HEX file) and only in or with products utilizing the Microsemi
 switch and PHY products.  The source code of the software may not be
 disclosed, transmitted or distributed without the prior written permission of
 Microsemi.

 This copyright notice must appear in any copy, modification, disclosure,
 transmission or distribution of the software.  Microsemi retains all
 ownership, copyright, trade secret and proprietary rights in the software and
 its source code, including all modifications thereto.

 THIS SOFTWARE HAS BEEN PROVIDED "AS IS". MICROSEMI HEREBY DISCLAIMS ALL
 WARRANTIES OF ANY KIND WITH RESPECT TO THE SOFTWARE, WHETHER SUCH WARRANTIES
 ARE EXPRESS, IMPLIED, STATUTORY OR OTHERWISE INCLUDING, WITHOUT LIMITATION,
 WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE AND
 NON-INFRINGEMENT.

*/
/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IPADDRESSTABLE_H
#define IPADDRESSTABLE_H

#define RFC4293_SUPPORTED_IPMIB
#define VTSS_HAS_PER_INTERFACE_IP_STATISTICS

#ifdef __cplusplus
extern "C" {
#endif
/*
 * function declarations
 */
void            init_ip(void);
//void            init_ipAddressTable(void);
FindVarMethod   var_ipAddressTable;
FindVarMethod   var_ipAddressTable;
WriteMethod     write_ipAddressIfIndex;
WriteMethod     write_ipAddressType;
WriteMethod     write_ipAddressStatus;
WriteMethod     write_ipAddressRowStatus;
WriteMethod     write_ipAddressStorageType;

//void            init_ipTrafficStats(void);
FindVarMethod   var_ipTrafficStats;
FindVarMethod   var_ipSystemStatsTable;
FindVarMethod   var_ipIfStatsTable;

//void            init_icmpStatsTable(void);
FindVarMethod   var_icmpStatsTable;
FindVarMethod   var_icmpStatsTable;

//void            init_icmpMsgStatsTable(void);
FindVarMethod   var_icmpMsgStatsTable;
FindVarMethod   var_icmpMsgStatsTable;

//void init_ipNetToPhysicalTable(void);
FindVarMethod var_ipNetToPhysicalTable;
FindVarMethod var_ipNetToPhysicalTable;
WriteMethod write_ipNetToPhysicalPhysAddress;
WriteMethod write_ipNetToPhysicalType;
WriteMethod write_ipNetToPhysicalRowStatus;

//void init_ipDefaultRouterTable(void);
FindVarMethod var_ipDefaultRouterTable;
FindVarMethod var_ipDefaultRouterTable;

//void init_ipv4InterfaceTable(void);
FindVarMethod var_ipv4InterfaceTable;
FindVarMethod var_ipv4InterfaceTable;
WriteMethod write_ipv4InterfaceEnableStatus;

//void init_ipv6InterfaceTable(void);
FindVarMethod var_ipv6InterfaceTable;
FindVarMethod var_ipv6InterfaceTable;
WriteMethod write_ipv6InterfaceEnableStatus;
WriteMethod write_ipv6InterfaceForwarding;

//void init_ipv6ScopeZoneIndexTable(void);
FindVarMethod var_ipv6ScopeZoneIndexTable;
FindVarMethod var_ipv6ScopeZoneIndexTable;

#ifdef __cplusplus
}
#endif
#endif                          /* IPADDRESSTABLE_H */
